import { Flashcard } from "../types";

export const africanCapitals: Flashcard[] = [
    { front: "Algeria", back: "Algiers" },
    { front: "Angola", back: "Luanda" },
    { front: "Benin", back: "Porto-Novo" },
    { front: "Botswana", back: "Gaborone" },
    { front: "Burkina Faso", back: "Ouagadougou" },
    { front: "Burundi", back: "Gitega" },
    { front: "Cabo Verde", back: "Praia" },
    { front: "Cameroon", back: "Yaounde" },
    { front: "Central African Republic", back: "Bangui" },
    { front: "Chad", back: "N'Djamena" },
    { front: "Comoros", back: "Moroni" },
    { front: "Congo, Democratic Republic of the", back: "Kinshasa" },
    { front: "Congo, Republic of the", back: "Brazzaville" },
    { front: "Cote d'Ivoire", back: "Yamoussoukro" },
    { front: "Djibouti", back: "Djibouti (city)" },
    { front: "Egypt", back: "Cairo" },
    { front: "Equatorial Guinea", back: "Malabo (de jure), Oyala (seat of government)" },
    { front: "Eritrea", back: "Asmara" },
    { front: "Eswatini", back: "Mbabane (administrative), Lobamba (legislative, royal)" },
    { front: "Ethiopia", back: "Addis Ababa" },
    { front: "Gabon", back: "Libreville" },
    { front: "Gambia", back: "Banjul" },
    { front: "Ghana", back: "Accra" },
    { front: "Guinea", back: "Conakry" },
    { front: "Guinea-Bissau", back: "Bissau" },
    { front: "Kenya", back: "Nairobi" },
    { front: "Lesotho", back: "Maseru" },
    { front: "Liberia", back: "Monrovia" },
    { front: "Libya", back: "Tripoli" },
    { front: "Madagascar", back: "Antananarivo" },
    { front: "Malawi", back: "Lilongwe" },
    { front: "Mali", back: "Bamako" },
    { front: "Mauritania", back: "Nouakchott" },
    { front: "Mauritius", back: "Port Louis" },
    { front: "Morocco", back: "Rabat" },
    { front: "Mozambique", back: "Maputo" },
    { front: "Namibia", back: "Windhoek" },
    { front: "Niger", back: "Niamey" },
    { front: "Nigeria", back: "Abuja" },
    { front: "Rwanda", back: "Kigali" },
    { front: "Sao Tome and Principe", back: "Sao Tome" },
    { front: "Senegal", back: "Dakar" },
    { front: "Seychelles", back: "Victoria" },
    { front: "Sierra Leone", back: "Freetown" },
    { front: "Somalia", back: "Mogadishu" },
    { front: "South Africa", back: "Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial)" },
    { front: "South Sudan", back: "Juba" },
    { front: "Sudan", back: "Khartoum" },
    { front: "Tanzania", back: "Dodoma" },
    { front: "Togo", back: "Lome" },
    { front: "Tunisia", back: "Tunis" },
    { front: "Uganda", back: "Kampala" },
    { front: "Zambia", back: "Lusaka" },
    { front: "Zimbabwe", back: "Harare" },
];