import { Flashcard } from "../types";

export const basicSpanish: Flashcard[] = [
    { front: "Yes", back: "Sí" },
    { front: "No", back: "No" },
    { front:"Do you understand?", back: "¿Entiendes?" },
    { front:"I don't understand", back: "No entiendo" },
    { front: "I don't speak spanish", back: "No hablo español" },
    { front: "Im lost", back: "Estoy perdido(a)" },
    { front: "My name is...", back: "Me llamo..." },
    { front: "What is your name?", back: "¿Cómo te llamas?" },
    { front: "I am from...", back: "Soy de..." },
    { front: "How are you?", back: "¿Cómo estás?" },
    { front: "Very good", back: "Muy bien" },
    { front: "So, so", back: "Así, así" },
    { front: "Bad", back: "Mal"},
    { front: "As always", back: "Como siempre" },
    { front: "You're welcome", back: "De nada" },
    { front: "Please", back: "Por favor" },
    { front: "Excuse me ", back: "Perdón" },
    { front: "Sorry", back: "Lo siento" },
    { front: "Thank you", back: "Gracias" },
    { front: "Bless you", back: "Salud" },
    { front: "What", back: "Qué" },
    { front: "Who", back: "Quién" },
    { front: "When", back: "Cuándo" },
    { front: "Where", back: "Dónde" },
    { front: "Why", back: "Por qué" },
    { front: "Which", back: "Cuál" },
    { front: "How", back: "Cómo" },
    { front: "I", back: "Yo" },
    { front: "You", back: "Tú" },
    { front: "He", back: "Él" },
    { front: "She", back: "Ella" },
    { front: "We", back: "Nosotros(as)" },
    { front: "They", back: "Ellos(as)" },
    { front: "Hello", back: "Hola" },
    { front: "Good morning", back: "Buenos días" },
    { front: "Good afternoon", back: "Buenas tardes" },
    { front: "Good evening", back: "Buenas noches" },
    { front: "Good night", back: "Buenas tardes" },
    { front: "Goodbye", back: "Adiós" },
    { front: "See you later", back: "Hasta luego" },
    { front: "See you tomorrow", back: "Hasta mañana" },
    { front: "Sunday", back: "Domingo" },
    { front: "Monday", back: "Lunes" },
    { front: "Tuesday", back: "Martes" },
    { front: "Wednesday", back: "Miércoles" },
    { front: "Thursday", back: "Jueves" },
    { front: "Friday", back: "Viernes" },
    { front: "Saturday", back: "Sábado" },
    { front: "January", back: "Enero" },
    { front: "February", back: "Febrero" },
    { front: "March", back: "Marzo" },
    { front: "April", back: "Abril" },
    { front: "May", back: "Mayo" },
    { front: "June", back: "Junio" },
    { front: "July", back: "Julio" },
    { front: "August", back: "Agosto" },
    { front: "September", back: "Septiembre" },
    { front: "October", back: "Octubre" },
    { front: "November", back: "Noviembre" },
    { front: "December", back: "Diciembre" },
    { front: "Yesterday", back: "Ayer" },
    { front: "Year", back: "Año" },
    { front: "Day", back: "Día" },
    { front: "Month", back: "Mes" },
    { front: "Hour", back: "Hora" },
    { front: "Today", back: "Hoy" },
    { front: "Week", back: "Semana" },
    { front: "Dawn", back: "Madrugada" },
    { front: "Tomorrow / Morning", back: "Mañana" },
    { front: "Midnight", back: "Medianoche" },
    { front: "Noon", back: "Mediodía" },
    { front: "Minute", back: "Minuto" },
    { front: "Night", back: "Noche" },
    { front: "Second", back: "Segundo" },
    { front: "Afternoon", back: "Tarde" },
    { front: "Father", back: "Padre" },
    { front: "Mother", back: "Madre" },
    { front: "Dad", back: "Papá" },
    { front: "Mom", back: "Mamá" },
    { front: "Brother", back: "Hermano" },
    { front: "Sister", back: "Hermana" },
    { front: "Son", back: "Hijo" },
    { front: "Daughter", back: "Hija" },
    { front: "Grandfather", back: "Abuelo" },
    { front: "Grandmother", back: "Abuela" },
    { front: "Grandson", back: "Nieto" },
    { front: "Granddaughter", back: "Nieta" },
    { front: "Uncle", back: "Tío" },
    { front: "Aunt", back: "Tía" },
    { front: "Cousin", back: "Primo/a" }
    // https://www.spanish.academy/blog/1000-most-common-spanish-words-for-beginners/#:~:text=perdonar%20%E2%80%94%20to%20forgive-,Action%20Verbs,-empezar%20%E2%80%94%C2%A0%20to
];

