 import { Flashcard } from "../types";

export const europeanCapitals: Flashcard[] = [
    { front: "Albania", back: "Tirana" },
    { front: "Andorra", back: "Andorra la Vella" },
    { front: "Armenia", back: "Yerevan" },
    { front: "Austria", back: "Vienna" },
    { front: "Azerbaijan", back: "Baku" },
    { front: "Belarus", back: "Minsk" },
    { front: "Belgium", back: "Brussels" },
    { front: "Bosnia and Herzegovina", back: "Sarajevo" },
    { front: "Bulgaria", back: "Sofia" },
    { front: "Croatia", back: "Zagreb" },
    { front: "Cyprus", back: "Nicosia" },
    { front: "Czech Republic", back: "Prague" },
    { front: "Denmark", back: "Copenhagen" },
    { front: "Estonia", back: "Tallinn" },
    { front: "Finland", back: "Helsinki" },
    { front: "France", back: "Paris" },
    { front: "Georgia", back: "Tbilisi" },
    { front: "Germany", back: "Berlin" },
    { front: "Greece", back: "Athens" },
    { front: "Hungary", back: "Budapest" },
    { front: "Iceland", back: "Reykjavik" },
    { front: "Ireland", back: "Dublin" },
    { front: "Italy", back: "Rome" },
    { front: "Kazakhstan", back: "Astana" },
    { front: "Kosovo", back: "Pristina" },
    { front: "Latvia", back: "Riga" },
    { front: "Liechtenstein", back: "Vaduz" },
    { front: "Lithuania", back: "Vilnius" },
    { front: "Luxembourg", back: "Luxembourg" },
    { front: "Malta", back: "Valletta" },
    { front: "Moldova", back: "Chisinau" },
    { front: "Monaco", back: "Monaco" },
    { front: "Montenegro", back: "Podgorica" },
    { front: "Netherlands", back: "Amsterdam" },
    { front: "North Macedonia", back: "Skopje" },
    { front: "Norway", back: "Oslo" },
    { front: "Poland", back: "Warsaw" },
    { front: "Portugal", back: "Lisbon" },
    { front: "Romania", back: "Bucharest" },
    { front: "Russia", back: "Moscow" },
    { front: "San Marino", back: "San Marino" },
    { front: "Serbia", back: "Belgrade" },
    { front: "Slovakia", back: "Bratislava" },
    { front: "Slovenia", back: "Ljubljana" },
    { front: "Spain", back: "Madrid" },
    { front: "Sweden", back: "Stockholm" },
    { front: "Switzerland", back: "Bern" },
    { front: "Turkey", back: "Ankara" },
    { front: "Ukraine", back: "Kyiv (Kiev)" },
    { front: "United Kingdom", back: "London" },
    { front: "Vatican City (Holy See)", back: "Vatican City" }
];